---
dependencies:
  another_flushbar: ^1.12.30
  audio_session: ^0.1.16
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.2.2
  expandable: ^5.0.1
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_html: ^2.2.1
  flutter_launcher_icons: ^0.11.0
  flutter_loggy: ^2.0.2
  flutter_native_splash: ^2.2.0+1
  flutter_sound: ^9.2.13
  flutter_svg: ^0.23.0+1
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  html: ^0.15.4
  image_picker: ^1.0.2
  intl: ^0.17.0
  path: ^1.8.2
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  persistent_bottom_nav_bar: ^5.0.2
  platform: ^3.1.1
  pull_to_refresh: ^2.0.0
  velocity_x: ^3.6.0
  very_good_analysis: ^4.0.0+1
description: Interactive learning for difabel.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.19.6 <3.0.0'
flutter:
  assets:
    - assets/images/
    - assets/fonts/
  uses-material-design: true
flutter_config:
  path: ../
flutter_icons:
  android: launcher_icon
  image_path: assets/images/ic_icon.png
  ios: true
  remove_alpha_ios: true
get_cli:
  sub_folder: false
name: andin_project
publish_to: none
version: 1.0.0+1