name: andin_project
version: 1.0.0+1
publish_to: none
description: Interactive learning for difabel.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.1.0
  flutter_config: ^2.0.2
  get_storage: ^2.1.1
  faker: ^2.1.0
  expandable: ^5.0.1
  audio_session: ^0.1.16
  device_info_plus: ^8.2.2
  html: ^0.15.4
  flutter_html: ^2.2.1
  intl: ^0.18.1
  flutter_sound: ^9.2.13
  flutter_svg: ^0.23.0+1
  flutter_loggy: ^2.0.2
  google_fonts: ^4.0.4
  image_picker: ^1.0.2
  permission_handler: ^10.4.3
  platform: ^3.1.1
  pull_to_refresh: ^2.0.0
  velocity_x: ^4.1.0
  build_runner: ^2.3.3
  flutter_native_splash: ^2.2.0+1
  flutter_launcher_icons: ^0.11.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
flutter_config:
  path: ../
flutter_icons:
  android: launcher_icon
  image_path: assets/images/ic_icon.png
  ios: true
  remove_alpha_ios: true
get_cli:
  sub_folder: false